model:
  checkpoint: ckpt/trained.pt
  target: 2ZSH_pocket10.pdb
  ligand: diffgui_run/scaffolds/oxadiazole_134_placed.sdf
  frag: diffgui_run/scaffolds/oxadiazole_134_frag_indices.txt
  gen_mode: frag_cond
  logp: 2.00
  tpsa: 80
  sa: 3.00
  qed: 0.60
  aff: 10.00

bond_predictor: ckpt/bond_trained.pt

sample:
  seed: 2024
  batch_size: 2
  num_mols: 200
  save_traj_prob: 0.0
  sample: True
  sample_method: priori
  mode: pocket
  add_edge: None
  gui_strength: 3.0
  guidance:
    - uncertainty
    - 1.e-4

data:
  name: protein_ligand
  path: data/PDBbind_v2020_pocket10
  split: data/PDBbind_pocket10_split.pt
  protein_root: data/PDBbind_v2020
  dataset: pdbbind
  transform:
    ligand_atom_mode: aromatic
    random_rot: False
    sample: False
